//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;

public class Contract : Document
{
	public string type;

	public override string ToString()
	{
        string line = "";
        line = "Первая персона:\n"+firstPerson.ToString()+"\nВторая персона:\n"+secondPerson.ToString()
            +"\nПуть к документу:"+linkToFolder+"\nСтоимость:"+cost+"\nОплата:"+payment+"\nТип:"+type.ToString();
        Process.Start(linkToFolder);
        return line;
	}

	public Contract(Person _fP, Person _sP, string _lTF, double _cost, bool _payment, string _type)
	{
        firstPerson = _fP;
        secondPerson = _sP;
        linkToFolder = _lTF;
        cost = _cost;
        payment = _payment;
        type = _type;
	}

	public virtual string Change(Person _fP, Person _sP, string _lTF, double _cost, bool _payment, string _type)
	{
        firstPerson = _fP;
        secondPerson = _sP;
        linkToFolder = _lTF;
        cost = _cost;
        payment = _payment;
        type=_type;
        return "Договор изменён";
	}

}

