//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Date
{
    private int day;

    private int month;

    private int year;


    public int Day
    {
        get
        {
            return day;
        }
        set
        {
            day = value;
        }
    }
    public int Month
    {
        get
        {
            return month;
        }
        set
        {
            month = value;
        }
    }
    public int Year
    {
        get
        {
            return year;
        }
        set
        {
            year = value;
        }
    }

    public virtual string ToString()
    {
        return Day + "." + Month + "." + Year;
    }
    public Date()
    {
        Day = DateTime.Now.Day;
        Month = DateTime.Now.Month;
        Year = DateTime.Now.Year;
    }
    public Date(int _day, int _month, int _year)
    {
        if (Change(_day, _month, _year) == false)
        {
            Day = DateTime.Now.Day;
            Month = DateTime.Now.Month;
            Year = DateTime.Now.Year;
        }
    }

    public virtual bool Change(int _day, int _month, int _year)
    {
        if (_day < 1 || (_day > 31 && Math.IEEERemainder(_month, 2) != 0 && _month != 2)
                || (_day > 30 && Math.IEEERemainder(_month, 2) == 0) || (_day > 28 && _month == 2) ||
            _month < 1 || _month > 12 ||
            _year < DateTime.Now.Year || _year > 2500)
        {
            return false;
        }
        Day = _day;
        Month = _month;
        Year = _year;
        return true;
    }
    public string StatusError(int _day, int _month, int _year)
    {
        string line = "";
        if (_year < DateTime.Now.Year)
        {
            line += "   Чтото год маловат";
        }
        else if (_year > 2500)
        {
            line += "   Чтото год большеват";
        }
        if (_month < 1)
        {
            line += "   Месяц не может быть отрицательеым или нулевым";
        }
        else if (_month > 12)
        {
            line += "   У нас всего 12 месяцев";
        }
        if (_day < 1)
        {
            line += "   День не может быть отрицательеым или нулевым";
        }
        else if (_month == 2 && _day > 28)
        {
            line += "   В феврале 28 дней";
        }
        else if (_month >= 1 && _month <= 12 && _day > 31 && Math.IEEERemainder(_month, 2) == 0 && _month != 2)
        {
            line += "   В " + _month + "-м месяце 31 день";
        }
        else if (_month >= 1 && _month <= 12 && _day > 30 && Math.IEEERemainder(_month, 2) != 0)
        {
            line += "   В " + _month + "-м месяце 30 день";
        }
        return line;
    }
    public static bool operator ==(Date obj1, Date obj2)
    {
        if ((obj1.Day == obj2.Day) && (obj1.Month == obj2.Month) && (obj1.Year == obj2.Year))
        {
            return true;
        }
        return false;
    }

    public static bool operator !=(Date obj1, Date obj2)
    {
        if ((obj1.Day != obj2.Day) || (obj1.Month != obj2.Month) || (obj1.Year != obj2.Year))
        {
            return true;
        }
        return false;
    }
}

