//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Document
{
	protected string linkToFolder;

	protected double cost;

	protected bool payment;

	protected Person secondPerson;

	protected Person firstPerson;

	public virtual string ToStringNumberCostPayment()
	{
        return "\nСтоимость:"+cost+"\nОплачен:"+payment;
	}

	public virtual string ToString()
	{
		throw new System.NotImplementedException();
	}
    public virtual string Change(bool payment, double cost)
    {
        throw new System.NotImplementedException();
    }
}

