//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class IPerson 
{
	protected string name;

	protected SortedList<int,Document> listDocument;

	protected string type;

	public virtual void Person()
	{
		throw new System.NotImplementedException();
	}

	public virtual string ToString()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool AddDocument(int number, Document document)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool DeleteDocument(int number)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool Change(string _name, string _type)
	{
		throw new System.NotImplementedException();
	}

	public virtual string ChangeErrorToString(string _name, string _type)
	{
		throw new System.NotImplementedException();
	}

}

