//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;

public class LawsuitAndClaim : Document
{
	private string court;

	private string status;

	private TypeLawsuitAndClaim type;

	public override string ToString()
	{
        string line = "";
        line = "Первая персона:\n" + firstPerson.ToString() + "\nВторая персона:\n" + secondPerson.ToString()
            + "\nПуть к документу:" + linkToFolder + "\nСтоимость:" + cost + "\nОплата:" + payment + "\nТип:";
        if (type == TypeLawsuitAndClaim.lawsuit)
        {
            line += "Иск";
        }
        else
        {
            line += "Претензия";
        }
        line += "\nСуд:" + court+"\nСтатус:"+status;
        Process.Start(linkToFolder);
        return line; ;
	}

	public LawsuitAndClaim(Person _fP, Person _sP, string _lTF, double _cost, bool _payment, string _court, string _status, TypeLawsuitAndClaim _type)
	{
        firstPerson = _fP;
        secondPerson = _sP;
        linkToFolder = _lTF;
        cost = _cost;
        payment = _payment;
        type = _type;
	}

	public virtual string Change(Person _fP, Person _sP, string _lTF, double _cost, bool _payment, string _court, string _status, TypeLawsuitAndClaim _type)
	{
        firstPerson = _fP;
        secondPerson = _sP;
        linkToFolder = _lTF;
        cost = _cost;
        payment = _payment;
        type = _type;
        return "Договор изменён";
	}

}

