//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;

public class LetterOfAttorney : Document
{
	private TypeLetterOfAttorney type;

	private Person thirdPerson;

	private string status;

	private Date dateOfConclusion;

	private Date dateOfExpiry;

	private bool expiry;

	public override string ToString()
	{
        string line = "";
        line = "Первая персона:\n" + firstPerson.ToString() + "\nВторая персона:\n" + secondPerson.ToString()+"\nТретья персона:\n"+thirdPerson.ToString()
            + "\nПуть к документу:" + linkToFolder + "\nСтоимость:" + cost + "\nОплата:" + payment + "\nТип:";
        if (type == TypeLetterOfAttorney.single)
        {
            line += "Одноразовый";
        }
        else
        {
            line += "На определённый интервал времени";
        }
        line += "\nСтатус:" + status + "\nДата заключения" + dateOfConclusion.ToString() + "\nДата истечения:"+dateOfExpiry.ToString() + "\nДойствительность:"+expiry;
        Process.Start(linkToFolder);
        return line;
	}

	public LetterOfAttorney(Person _fP, Person _sP, Person _tP, string _lTF, double _cost, bool _payment, Date _dOC, Date _dOE, bool _expiry, string _status, TypeLetterOfAttorney _type)
	{
        firstPerson = _fP;
        secondPerson = _sP;
        thirdPerson = _tP;
        linkToFolder = _lTF;
        cost = _cost;
        payment = _payment;
        dateOfConclusion = _dOC;
        dateOfExpiry = _dOE;
        expiry = _expiry;
        status = _status;
        type = _type;
	}

	public virtual string Change(Person _fP, Person _sP, Person _tP, string _lTF, double _cost, bool _payment, Date _dOC, Date _dOE, bool _expiry, string _status, TypeLetterOfAttorney _type)
	{
        firstPerson = _fP;
        secondPerson = _sP;
        thirdPerson = _tP;
        linkToFolder = _lTF;
        cost = _cost;
        payment = _payment;
        dateOfConclusion = _dOC;
        dateOfExpiry = _dOE;
        expiry = _expiry;
        status = _status;
        type = _type;
        return "Довереность изменена";
	}

}

