//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Person : IPerson
{
    public Person()
    {
        name = "Иванов Иван Иванович";
        type = "Физическое лицо";
    }

    public override string ToString()
    {
        string line = "\n-Имя:" + type + "-Тип:" + name + "-";
        foreach (int i in listDocument.Keys)
        {
            line += "Документ номер " + i + ":" + listDocument[i].ToString() + "-\n";
        }
        return line;
    }

    public override bool AddDocument(int number, Document document)
    {
        if (listDocument.Keys.Contains(number) == false)
        {
            listDocument.Add(number, document);
            return true;
        }
        return false;
    }

    public override bool DeleteDocument(int number)
    {
        if (listDocument.Keys.Contains(number) == true)
        {
            listDocument.Remove(number);
            return true;
        }
        return false;
    }

    public override bool Change(string _name, string _type)
    {
        if (string.IsNullOrWhiteSpace(_name) == true || string.IsNullOrWhiteSpace(_type) == true)
        {
            return false;
        }
        else
        {
            if (string.Compare(_type, "Физическое лицо") == 0)
            {
                char[] separator = { ' ' };
                string[] stringArray = _name.Split(separator,StringSplitOptions.RemoveEmptyEntries);
                if (stringArray.Length == 3)
                {
                    name = _name;
                    type = _type;
                    return true;
                }
                else
                {
                    return false;
                }
            }
            else if (string.Compare(_type, "Юридическое лицо") == 0)
            {
                name = _name;
                type = _type;
                return true;
            }
            else
            {
                return false;
            }
        }
    }

    public override string ChangeErrorToString(string _name, string _type)
    {
        string line = "";
        if (string.Compare(_type, "Физическое лицо") == 0)
        {
            char[] separator = { ' ' };
            string[] stringArray = _name.Split(separator, StringSplitOptions.RemoveEmptyEntries);
            if (stringArray.Length == 3)
            {

            }
            else
            {
                line += "Имя должно быть из 3-х слов ";
            }
        }
        else if (string.Compare(_type, "Юридическое лицо") == 0)
        {
        }
        else
        {
            if (string.IsNullOrWhiteSpace(_name) == true)
            {
                line += "Имя не может быть пустым ";
            }
            if (string.IsNullOrWhiteSpace(_type) == true)
            {
                line += "Тип не может быть пустым ";
            }
            else
            {
                line += "Ошибка типа ";
            }
        }
        return line;
    }
}

