//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Time
{
    private int hour;

    private int minute;



    public int Hour
    {
        get
        {
            return hour;
        }
        set
        {
            hour = value;
        }
    }

    public int Minute
    {
        get
        {
            return minute;
        }
        set
        {
            minute = value;
        }
    }

    public virtual string ToString()
    {
        return Hour + ":" + Minute;
    }

    public Time()
    {
        Hour = DateTime.Now.Hour;
        Minute = DateTime.Now.Minute;
    }
    public Time(int _hour, int _minute)
    {
        if (Change(_hour, _minute) == false)
        {
            Hour = DateTime.Now.Hour;
            Minute = DateTime.Now.Minute;
        }
    }

    public virtual bool Change(int _hour, int _minute)
    {
        if (_hour < 8 || _hour > 17 || _minute < 0 || _minute >= 60)
        {
            return false;
        }
        Hour = _hour;
        Minute = _minute;
        return true;
    }
    public string StatusError(int _hour, int _minute)
    {
        string line = "";
        if (_hour < 0)
        {
            line += "   Час не может быть отрицательным";
        }
        else if (_hour < 8)
        {
            line += "   Фирма работает с 8-ми";
        }
        else if (_hour > 23)
        {
            line += "   В сутках 24 часа";
        }
        else if (_hour > 17)
        {
            line += "   Фирма работает до 18-ти";
        }
        if (_minute < 0)
        {
            line += "   Минуты не могут быть отрицательными";
        }
        else if (_minute > 59)
        {
            line += "   В часе 60 минут\n";
        }
        return line;
    }
    public static bool operator ==(Time obj1, Time obj2)
    {
        if ((obj1.Hour == obj2.Hour) && (obj1.Minute == obj2.Minute))
        {
            return true;
        }
        return false;
    }

    public static bool operator !=(Time obj1, Time obj2)
    {
        if ((obj1.Hour != obj2.Hour) || (obj1.Minute != obj2.Minute))
        {
            return true;
        }
        return false;
    }
}

